apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcpserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcpserver
  template:
    metadata:
      labels:
        app: mcpserver
    spec:
      containers:
        - name: mcpserver
          image: mcpserver:latest
          envFrom:
            - configMapRef:
                name: mcp-config
            - secretRef:
                name: mcp-secrets
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: db
              mountPath: /app/db
            - name: logs
              mountPath: /app/logs
      volumes:
        - name: db
          emptyDir: {}
        - name: logs
          emptyDir: {}